# Generated by Django 2.2.13 on 2020-11-20 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateTimeField(auto_now_add=True)),
                ('parsed_text', models.TextField(default='Name of file for generating music', max_length=5000)),
                ('parsed_music', models.FileField(upload_to='generated_music/')),
                ('report', jsonfield.fields.JSONField(verbose_name={})),
                ('developer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
