# Generated by Django 2.2.13 on 2020-11-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_musicreportmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicreportmodel',
            name='parsed_music',
            field=models.TextField(max_length=5000),
        ),
    ]
